name: Run API Tests

on:
  push:
    branches:
      - main
      - first-api-branch
  schedule:
    - cron: '0 0 * * 5'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Build and test
        run: mvn clean test
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
      - name: Install Allure CLI
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip allure-2.27.0.zip -d /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure
      - name: Generate Allure HTML Report
        run: |
          allure generate allure-results --clean -o allure-report
      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report/
